=== sebsca/ectd-tool/tests/fixtures/tool/ich-ectd-3-2.dtd
<!-- Synthetic eCTD subset for implementation tests, not a regulatory schema. -->
<!ELEMENT ectd:ectd (m1-administrative-information-and-prescribing-information?,m2-common-technical-document-summaries?,m3-quality?,m4-nonclinical-study-reports?,m5-clinical-study-reports?)>
<!ATTLIST ectd:ectd xmlns:ectd CDATA #FIXED "http://www.ich.org/ectd" xmlns:xlink CDATA #FIXED "http://www.w3.org/1999/xlink" dtd-version CDATA #FIXED "3.2">
<!ELEMENT m1-administrative-information-and-prescribing-information (leaf*)>
<!ELEMENT m2-common-technical-document-summaries (m2-2-introduction?,m2-3-quality-overall-summary?)>
<!ELEMENT m2-2-introduction (leaf*)>
<!ELEMENT m2-3-quality-overall-summary (leaf*,m2-3-introduction*,m2-3-s-drug-substance*)>
<!ELEMENT m2-3-introduction (leaf*)>
<!ELEMENT m2-3-s-drug-substance (leaf*)>
<!ATTLIST m2-3-s-drug-substance substance CDATA #IMPLIED manufacturer CDATA #IMPLIED>
<!ELEMENT m3-quality (m3-2-body-of-data?)>
<!ELEMENT m3-2-body-of-data (m3-2-s-drug-substance*)>
<!ELEMENT m3-2-s-drug-substance (leaf*,m3-2-s-1-general-information*)>
<!ATTLIST m3-2-s-drug-substance substance CDATA #IMPLIED manufacturer CDATA #IMPLIED>
<!ELEMENT m3-2-s-1-general-information (leaf*)>
<!ELEMENT m4-nonclinical-study-reports (leaf*)>
<!ELEMENT m5-clinical-study-reports (leaf*)>
<!ELEMENT leaf (title)>
<!ATTLIST leaf ID ID #REQUIRED checksum CDATA #REQUIRED checksum-type (MD5) #REQUIRED operation (new|replace|append|delete) #REQUIRED xlink:href CDATA #IMPLIED modified-file CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>

=== sebsca/ectd-tool/examples/demo-dossier/0000/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ectd:ectd SYSTEM "util/dtd/ich-ectd-3-2.dtd">
<ectd:ectd xmlns:ectd="http://www.ich.org/ectd" xmlns:xlink="http://www.w3.org/1999/xlink" dtd-version="3.2">
  <m1-administrative-information-and-prescribing-information>
    <leaf ID="regional-0000" operation="new" xlink:href="m1/eu/eu-regional.xml">
      <title>EU regional backbone</title>
    </leaf>
  </m1-administrative-information-and-prescribing-information>
  <m2-common-technical-document-summaries>
    <m2-3-quality-overall-summary>
      <leaf ID="summary-v1" operation="new" xlink:href="m2/summary.txt" checksum="example-only" checksum-type="md5">
        <title>Quality &amp; safety overview</title>
        <extension category="demo"><note language="en">Complete nested metadata</note></extension>
      </leaf>
    </m2-3-quality-overall-summary>
  </m2-common-technical-document-summaries>
  <m3-quality>
    <m3-2-body-of-data>
      <m3-2-s-drug-substance substance="Demo substance" manufacturer="Example manufacturer">
        <leaf ID="substance-v1" operation="new" xlink:href="m3/substance.txt"><title>Drug substance</title></leaf>
      </m3-2-s-drug-substance>
    </m3-2-body-of-data>
  </m3-quality>
</ectd:ectd>
